name: tama-id-au

default-extensions:
  - OverloadedStrings
  - ExtendedDefaultRules

ghc-options:
  - -Wall

dependencies:
  - base
  - containers
  - lucid
  - clay
  - text

executable:
  main: Main.hs
  source-dirs: src